version: '3.7'

services:
  react-docker:
    image: react-docker
    build: .
    environment:
      NODE_ENV: development
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - 4000:8080
